version: '3'
networks:
  net-openea:

services:
  eap-admin-vue:
    image: szopen/eap-fast-vue:1.0.0
    container_name: eap-fast-vue
    ports:
      - 7086:80
    depends_on:
      - eap-fast-rest
    links:
      - eap-fast-rest:eap-fast
    networks:
      - net-openea
  eap-fast-rest:
    image: szopen/eap-fast:1.0.0
    container_name: eap-fast-rest
    environment:
      - spring.profiles.active=test
    depends_on:
      - eap-fast-mysql
    links:
      - eap-fast-mysql:eap-mysql
    networks:
      - net-openea
  eap-fast-mysql:
    image: szopen/mysql:5.7-utf8
    container_name: eap-fast-mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=localhost
      - MYSQL_DATABASE=eap_fast
      - MYSQL_USER=eap
      - MYSQL_PASSWORD=eap
    volumes:
      - eap-fast-mysql-data:/var/lib/mysql
    networks:
      - net-openea

volumes:
  eap-fast-mysql-data:
