version: '3'
networks:
  net-openea:

services:
  eap-oauth:
    image: szopen/eap-oauth:bpm-1.0.0
    container_name: eap-oauth
    environment:
      - spring.profiles.active=bpm
    ports:
      - 7010:8080
    depends_on:
      - eap-admin-rest
    networks:
      - net-openea

  eap-admin-ui:
    image: szopen/eap-admin-ui:iview-1.0.0
    container_name: eap-admin-ui
    ports:
      - 7020:80
    depends_on:
      - eap-admin-rest
    networks:
      - net-openea

  eap-admin-rest:
    image: szopen/eap-admin-rest:bpm-1.0.0
    container_name: eap-admin-rest
    environment:
      - spring.profiles.active=bpm
      - redis_host=eap-redis
    depends_on:
      - eap-admin-mysql
    links:
      - eap-admin-mysql:mysql
    restart: always
    networks:
      - net-openea

  eap-bpm-ui:
    image: szopen/eap-bpm-ui:1.0.0
    container_name: eap-bpm-ui
    ports:
      - 7030:80
    depends_on:
      - eap-bpm-rest
    links:
      - eap-bpm-rest:bpm-rest
    networks:
      - net-openea

  eap-bpm-rest:
    image: szopen/eap-bpm-rest:1.0.0
    container_name: eap-bpm-rest
    environment:
      - spring.profiles.active=eap
      - redis_host=eap-redis
      - jwt_enabled=false
    depends_on:
      - eap-bpm-mysql
    links:
      - eap-bpm-mysql:mysql
    restart: always
    networks:
      - net-openea

  eap-bpm-mysql:
    image: szopen/mysql:5.7-utf8
    container_name: eap-bpm-mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=localhost
      - MYSQL_DATABASE=eap_bpm
      - MYSQL_USER=eap
      - MYSQL_PASSWORD=eap
    volumes:
      - eap-bpm-mysql-data:/var/lib/mysql
    networks:
      - net-openea

  eap-admin-mysql:
    image: szopen/mysql:5.7-utf8
    container_name: eap-admin-mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=localhost
      - MYSQL_DATABASE=eap_admin
      - MYSQL_USER=eap
      - MYSQL_PASSWORD=eap
    volumes:
      - eap-admin-mysql-data:/var/lib/mysql
    networks:
      - net-openea

volumes:
  eap-bpm-mysql-data:
  eap-admin-mysql-data:
